# Importing Libraries

In [1]:
import pandas as pd
import numpy as np

# Loading Dataset

In [2]:
df = pd.read_csv("employee_records.csv (1).xls")

In [3]:
df

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22
...,...,...,...,...,...,...,...,...
29995,29996,Mia Brown,42,Australia,Support,Manager,133474.82,2015-07-03
29996,29997,Mason Thomas,41,Mexico,Engineering,Assistant,140793.59,2023-10-12
29997,29998,Lily Anderson,44,India,Marketing,Developer,68464.72,2021-06-28
29998,29999,Mason Taylor,46,Brazil,Finance,Assistant,148323.28,2017-11-11
29999,30000,Lucas Jackson,30,Mexico,Finance,Developer,93451.72,2017-03-17

In [4]:
df.head()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22

In [5]:
df.columns

Index(['Employee_ID', 'Employee_Name', 'Age', 'Country', 'Department',
       'Position', 'Salary', 'Joining_Date'],
      dtype='object')

In [6]:
df.isnull().sum()

Employee_ID      0
Employee_Name    0
Age              0
Country          0
Department       0
Position         0
Salary           0
Joining_Date     0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.describe()

        Employee_ID           Age         Salary
count  30000.000000  30000.000000   30000.000000
mean   15000.500000     40.978067   89826.142610
std     8660.398374     11.234432   34625.270533
min        1.000000     22.000000   30004.780000
25%     7500.750000     31.000000   59546.715000
50%    15000.500000     41.000000   89544.810000
75%    22500.250000     51.000000  119836.545000
max    30000.000000     60.000000  149996.390000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee_ID    30000 non-null  int64
 1   Employee_Name  30000 non-null  object
 2   Age            30000 non-null  int64
 3   Country        30000 non-null  object
 4   Department     30000 non-null  object
 5   Position       30000 non-null  object
 6   Salary         30000 non-null  float64
 7   Joining_Date   30000 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.8+ MB

In [10]:
df.shape

(30000, 8)

In [11]:
df['Salary'].fillna(df['Salary'].median(), inplace=True)
df['Age'].fillna(df['Age'].mean(), inplace=True)
df.head()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_15200\550409649.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].median(), inplace=True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_15200\550409649.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22

In [12]:
# Convert Joining_Date to datetime
df['Joining_Date'] = pd.to_datetime(df['Joining_Date'])
df.head()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22

# Handling Outliers

In [13]:
Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['Salary'] < lower) | (df['Salary'] > upper)]

In [14]:
# removing outliers
df = df[(df['Salary'] >= lower) & (df['Salary'] <= upper)]
df.head()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22

# Detect Outliers Using Z-score

In [15]:
# Calculate Z-score
df['Salary_zscore'] = (
    df['Salary'] - df['Salary'].mean()
) / df['Salary'].std()

df.head()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date,Salary_zscore
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04,1.514852
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13,0.251927
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30,-0.123040
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17,-1.597460
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22,-1.284796

In [16]:
outliers = df[abs(df['Salary_zscore']) > 3]

In [17]:
# remove outliers
df = df[abs(df['Salary_zscore']) <= 3]
df.head()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date,Salary_zscore
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04,1.514852
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13,0.251927
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30,-0.123040
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17,-1.597460
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22,-1.284796

# Log Tranformation

In [18]:
df['Salary_log'] = np.log1p(df['Salary'])
df.head()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date,Salary_zscore,Salary_log
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04,1.514852,11.865547
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13,0.251927,11.498321
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30,-0.123040,11.357053
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17,-1.597460,10.449140
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22,-1.284796,10.721961

# Square Root Transformation

In [19]:
df['Salary_sqrt'] = np.sqrt(df['Salary'])
df.head()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date,Salary_zscore,Salary_log,Salary_sqrt
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04,1.514852,11.865547,377.197985
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13,0.251927,11.498321,313.925469
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30,-0.123040,11.357053,292.516393
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17,-1.597460,10.449140,185.778551
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22,-1.284796,10.721961,212.931257

# Binning

In [20]:
'''bins = [20000,30000,60000,100000]
labels = ['Low','Medium','High']

df['Salary_Category'] = pd.cut(df['Salary'], bins=bins, labels=labels)

df.head()
'''

"bins = [20000,30000,60000,100000]\nlabels = ['Low','Medium','High']\n\ndf['Salary_Category'] = pd.cut(df['Salary'], bins=bins, labels=labels)\n\ndf.head()\n"

# Min-Max Normalization

In [21]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df['Salary_MinMax'] = scaler.fit_transform(df[['Salary']])

df.head()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date,Salary_zscore,Salary_log,Salary_sqrt,Salary_MinMax
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04,1.514852,11.865547,377.197985,0.935678
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13,0.251927,11.498321,313.925469,0.571243
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30,-0.123040,11.357053,292.516393,0.463041
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17,-1.597460,10.449140,185.778551,0.037577
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22,-1.284796,10.721961,212.931257,0.127800

# Decimal Normalization

In [22]:
j = len(str(int(df['Salary'].abs().max())))

# decimal scaling normalization
df['Salary_decimal_scaled'] = df['Salary'] / (10 ** j)
df.head()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date,Salary_zscore,Salary_log,Salary_sqrt,Salary_MinMax,Salary_decimal_scaled
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04,1.514852,11.865547,377.197985,0.935678,0.142278
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13,0.251927,11.498321,313.925469,0.571243,0.098549
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30,-0.123040,11.357053,292.516393,0.463041,0.085566
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17,-1.597460,10.449140,185.778551,0.037577,0.034514
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22,-1.284796,10.721961,212.931257,0.127800,0.045340

# Max Normalization

In [23]:
df['Salary_max_norm'] = df['Salary'] / df['Salary'].max()

df.head()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date,Salary_zscore,Salary_log,Salary_sqrt,Salary_MinMax,Salary_decimal_scaled,Salary_max_norm
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04,1.514852,11.865547,377.197985,0.935678,0.142278,0.948545
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13,0.251927,11.498321,313.925469,0.571243,0.098549,0.657010
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30,-0.123040,11.357053,292.516393,0.463041,0.085566,0.570453
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17,-1.597460,10.449140,185.778551,0.037577,0.034514,0.230097
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22,-1.284796,10.721961,212.931257,0.127800,0.045340,0.302272

In [24]:
df.columns

Index(['Employee_ID', 'Employee_Name', 'Age', 'Country', 'Department',
       'Position', 'Salary', 'Joining_Date', 'Salary_zscore', 'Salary_log',
       'Salary_sqrt', 'Salary_MinMax', 'Salary_decimal_scaled',
       'Salary_max_norm'],
      dtype='object')

In [25]:
print("Cleaned Dataset: ")
df.head()

Cleaned Dataset:

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date,Salary_zscore,Salary_log,Salary_sqrt,Salary_MinMax,Salary_decimal_scaled,Salary_max_norm
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04,1.514852,11.865547,377.197985,0.935678,0.142278,0.948545
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13,0.251927,11.498321,313.925469,0.571243,0.098549,0.657010
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30,-0.123040,11.357053,292.516393,0.463041,0.085566,0.570453
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17,-1.597460,10.449140,185.778551,0.037577,0.034514,0.230097
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22,-1.284796,10.721961,212.931257,0.127800,0.045340,0.302272